### ISSUE TITLE
Cannot use "yourself" as variable name in strict mode

### ISSUE THREAD

**Issue by mikesep** [gaborsch/rocky#27]
`yourself` is a [Rocky OOP `self` alias](https://github.com/gaborsch/rocky/blob/master/OOP.md#special-references). I'd like to be able to use it as a variable name in strict mode.

```console
$ cat yourself.rock
Confidence is key
Put confidence in yourself
Shout yourself

$ ./rockstar run --strict yourself.rock
Error: Self reference in a non-class context
  yourself.rock:3 (yourself.rock L0): Shout yourself
```

I think this is the code that needs to be skipped, but I'm not sure the best way to pass a strict mode parameter down through the layers:
https://github.com/gaborsch/rocky/blob/11d21fdac0b89751c751990bfb9ee6daa106c050/src/rockstar/expression/VariableReference.java#L48-L50

**Comment by gaborsch** [comment]
Now I moved most keywords (except the statement keywords) into `Keyword.java`. In that file adding a `+` sign before the keyword literal specifies that the keyword in that meaning will be used only in extended mode - so the `yourself` value got prefixed, too.
