### ISSUE TITLE
Increase maximum number of allowed iterations

### ISSUE THREAD

**Issue by hugobuddel** [gaborsch/rocky#28]
The current maximum of 1000 iterations is too low to solve the first day of this years advent of code, which requires 2000 iterations (in a naive implementation). Proposal is to enhance the limit to 10000.

* Advent of code (requires login to get puzzle input, because it is personal): https://adventofcode.com/2021/day/1
* My puzzle input: https://gitlab.astro.rug.nl/buddel/adventofcode/-/blob/master/2021/guile/day01/puzzle.txt
* My initial solution: https://gitlab.astro.rug.nl/buddel/adventofcode/-/blob/master/2021/rockstar/day01.rock

```
rockstar day01.rock < puzzle.txt 
Error: Loop exceeded 1000 iterations
  day01.rock:3 (day01.rock L0): While it ain't nothing
```

By the way, I don't feel comfortable making a PR because I cannot compile rocky, I'll create another issue for that.

**Comment by gaborsch** [comment]
There is an option `--infinite-loops` which turns off this loop limit. This is a safety feature - if you feel 1000 is not enough, I'm open to raise the default limit as well.

```
$ ./rockstar help run
Rockstar Java by gaborsch, Version 2.0.1 (with OOP)
---------------------------------------------------
Usage:
rockstar <filename> ...
rockstar run [--options ...] <filename> ...
    Execute a program. Input is taken from standard input, output is printed to standard output.
    All files use the same context.
Options:
    --infinite-loops
        Loops can run infinitely. Default: maximum 1000 cycles per loop (for safety reasons)
    --runlog
        Log the execution path to the stdout
    --exprlog
        Log the execution path and expression evaluations to the stdout
    --dec64
        Uses Dec64 arithmetic instead of the default IEEE754 (Double precision)
    -S --strict
        Strictly follow the syntax of the reference specification
```

**Comment by hugobuddel** [comment]
#35 adds the suggestion to use `--infinite-loops` to the error message, that makes the feature easier to discover

**Comment by gaborsch** [comment]
I increased the maximum number to 10000.
