### ISSUE TITLE
How to resolve `The J2SE Platform is not correctly set up.` error?

### ISSUE THREAD

**Issue by hugobuddel** [gaborsch/rocky#29]
I get the error below when trying to compile rocky. How can that error be resolved?

I don't have much experience with java development. Both openjdk and ant are installed through conda. I tried downgrading to openjdk 8, since the error message references JDK8, but that didn't work either.

```
$ ant -version
Apache Ant(TM) version 1.10.12 compiled on December 1 2021

$ java -version
openjdk version "11.0.9.1-internal" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 11.0.9.1-internal+0-adhoc..src, mixed mode)

$ ant jar
Buildfile: /[..]/rocky/build.xml

-pre-init:

-init-private:

-init-user:

-init-project:

-init-macrodef-property:

-init-modules-supported:

-do-init:

BUILD FAILED
/[..]/rocky/nbproject/build-impl.xml:151: The J2SE Platform is not correctly set up.
 Your active platform is: JDK8, but the corresponding property "platforms.JDK8.home" is not found in the project's properties files. 
 Either open the project in the IDE and setup the Platform with the same name or add it manually.
 For example like this:
     ant -Duser.properties.file=<path_to_property_file> jar (where you put the property "platforms.JDK8.home" in a .properties file)
  or ant -Dplatforms.JDK8.home=<path_to_JDK_home> jar (where no properties file is used)

Total time: 0 seconds
```

**Comment by hugobuddel** [comment]
Apparently this works:
```
ant -Dplatforms.JDK8.home="${JAVA_HOME}" jar
```
I don't understand why it is necessary to specify this manually, but it works.

Is this specific to my machine or something that would be worthwhile to add to the documentation?

**Comment by gaborsch** [comment]
Thanks for recommending a workaround, Actually it seems that there are too much IDE-specific settings in the ant `build.xml`, I need to set up a different build system, probably Maven.

I will leave tihs issue open until there's a final solution.

**Comment by gaborsch** [comment]
I moved the build system to Maven, removed the tightly coupled Ant files. It should run smoothly now.
