### ISSUE TITLE
Incompatibility with web interpreter (probably string comparison)

### ISSUE THREAD

**Issue by hugobuddel** [gaborsch/rocky#30]
This program (`day01.rock`)
```rockstar
My desire is irrevocable
Listen to my hate
While it ain't nothing
Listen to your love
If my hate is weaker than your love
Build my desire up

Put your love into my hate

Whisper my desire
```
with this input (`example.txt`)
```
199
200
208
210
200
207
240
269
260
263
```
results in output of 8 in [the online interpreter](https://codewithrockstar.com/online), but in 9 with rocky:
```
$ rockstar day01.rock < example.txt 
9
```

The code is the (buggy) solution to the first part of the first day of this years advent of code: https://adventofcode.com/2021/day/1

The problem might be due to string comparison. (Also, I do not know which implementation is the correct one, only that they differ.)

**Comment by hugobuddel** [comment]
I think the incompatibility is that `Listen` will convert numbers to integers in rocky, while they stay strings in the web interpreter (Satriani), but not sure.

**Comment by gaborsch** [comment]
Yes, your guess is correct. Before Rockstar having the `cast` statement (which - among others - parses a string into a number) it was impossible to enter a number and have a numeric value  - this was an feature in Rocky, that now became obsolate.

**Comment by gaborsch** [comment]
Fixed in https://github.com/gaborsch/rocky/commit/ec91a6bc10f70ea184d0705a8f696c8697f26a1f
