### ISSUE TITLE
Array length comparison incompatibility with Satriani

### ISSUE THREAD

**Issue by hugobuddel** [gaborsch/rocky#32]
The follow program behaves differently in Rocky than in Satriani:
```
The word is "abcde"
Shatter the word

If the word is 5
Shout "Five A"

If the word is stronger than 4 and the word is weaker than 6
Shout "Five B"

Let the word be the word times 1
If the word is 5
Shout "Five C"
```

Rocky accepts all three comparisons:
```
Five A
Five B
Five C
```

However Satriani requires an explicit cast (the `times 1`) for the `is` comparison to work:
```
Five B
Five C
```

The behavior of Rocky seems more sensible than that of Satriani, so maybe it should be kept. It took me by surprise though: https://gitlab.astro.rug.nl/buddel/adventofcode/-/commit/dc8d7237313cbfbb812e7ba3ca5d2177a1c84128

**Comment by gaborsch** [comment]
Recently there was a discussion about re-thinking the implementation of Arrays. Unfortunately the latest modifications are WIP in Rocky at the moment,

**Comment by gaborsch** [comment]
I 'd leave it as-is.  Rocky's implementation makes more sense, Worth to file a PR for Satriani - but because Rockstar 2.0 is underway I'd but little effort into it.
