### ISSUE TITLE
Assignments with equal sign do not work (and do work in Satriani)

### ISSUE THREAD

**Issue by hugobuddel** [gaborsch/rocky#33]
The following program does work in the online Satriani interpreter, but not in Rocky:
```
Answer = 42
Say answer
```

Satriani:
```
42
```

Rocky:
```
Error: Executing invalid statement on line 1
```

Using `=` for assignment isn't idiomatic anyway, so perhaps it is not worthwhile to fix this.

BTW, I'm just noting these incompatibilities as I study to become a Rockstar developer. If nothing else they can serve as a reference to other developers.

**Comment by gaborsch** [comment]
Assignment with `=` is not part of the [language specification](https://github.com/RockstarLang/rockstar/blob/main/spec.md) - good catch, actually. We should raise this question on [Rockstar issues](https://github.com/RockstarLang/rockstar/issues).

**Comment by gaborsch** [comment]
Fixed in https://github.com/gaborsch/rocky/commit/1f857296b0a71667d5818dcb41e01e1d8469fa07
