### ISSUE TITLE
incompatibility with Satriani when rocking nothing

### ISSUE THREAD

**Issue by hugobuddel** [gaborsch/rocky#38]
Rocking nothing will create a new array in rocky, while it appends in satriani. That is, this program will return 1 in rocky, and 2 in satriani:
```
the world is nothing
rock the world with 42
say the world
```

Same when `nothing` is replaced by `null` or `mysterious`. However both return 2 when `nothing` is replaced by some value.

I prefer the rocky behavior, because I used this feature to reset an existing array. The shortest way I can do it with the satriani behavir is like this:
```
(building the world)
rock the world with 1
rock the world with 2
rock the world with 3

(resetting the world to be an empty array)
the world is -1
rock the world with -2
roll the world
roll the world

(rebuilding the world better)
rock the world with 42
say the world
```
(Or rolling in a loop.)

So maybe not necessary to change this, but noting it here because it is an incompatibility that is good to be aware of.

**Comment by gaborsch** [comment]
I'm glad you liked Rocky behavior, but for the sake of compatibility I switched to Satriani's way.
