### ISSUE TITLE
Incompatibility string plus array, and array plus integer

### ISSUE THREAD

**Issue by hugobuddel** [gaborsch/rocky#39]
There is an incompatibility between satriani and rocky w.r.t. adding arrays to strings. See the following program:
```
rock the world
say "the world " plus the world
say "the world " plus 42
```
output in satriani:
```
the world 0
the world 42
```
output in rocky:
```
1
the world 42
```

See also this program (which also shows adding an integer to an array):
```
rock the world with 1
rock the world with 9
let space be the world with 4
let time be the world times 1
say the world
say space
say time
say "something " plus the world
say the world plus " something"
say "something " plus 2
```

satriani:
```
2
6
2
something 2
2 something
something 2
```

rocky:
```
2
3
2
3
3
something 2
```

My main concern is that I would like to use `array with 0` to get the length of an array, but in rocky it gets one more than the length of the array. Luckily this is not so bad, because apparently my songs also work with that.

**Comment by hugobuddel** [comment]
I'm particularly puzzled by "array plus integer", which always seems to result in the length of the array plus 1, irrespective of the value of the integer. "array minus integer" is even more interesting. It returns the length of the array minus 1, irrespective of the integer value (similar to the plus-case). But it gives an error if the integer value is larger than the size of the array.

```
rock the world with 17
rock the world with 9
rock the world with 27

let space be the world with 5
say space

let time be the world without 0
say time

let singularity be the world without 7
say singularity
```

satriani:
```
8
3
-4
```

rocky:
```
4
2
Error: Index 7 out of bounds for length 3
```

**Comment by gaborsch** [comment]
Fixed.
