### ISSUE TITLE
Uniting mysterious and mysterious plus string incompatibility

### ISSUE THREAD

**Issue by hugobuddel** [gaborsch/rocky#40]
Uniting an array with mysterious is different in rocky and satriani, as well as adding a string to mysterious:
```
rock the world
let the world at 3 be "A"
let the world at 5 be "B"

say the world at 2

unite the world
say the world

let the song be mysterious with "D"
say the song
```

satriani:
```
mysterious
AB
mysteriousD
```

rocky:
```
mysterious
mysteriousmysteriousmysteriousAmysteriousB
mysterious
```

I don't particularly have a preference for either these implementations, just noting that they are different.

**Comment by gaborsch** [comment]
Seems like Satriani skips the empty indices, while Rocky considers them as `mysterious`, as the spec says.  Probably the `unite` specification should be extended to cover this case.
Satriani treats `null` and array values similarly, skipping them entirely.
