### ISSUE TITLE
Order of operations for compound assignments

### ISSUE THREAD

**Issue by mikesep** [gaborsch/rocky#45]
Hi @gaborsch, I haven't written up a test PR yet, but I found a discrepancy between Rocky and Satriani, and I think I prefer what Satriani's doing.

Here's my example code:
```rockstar
total is 2
let total be of 3 with 5
shout it
```
Satriani prints `16`, but Rocky prints `11`.

If `be of` is like `*=` in other languages, then I think the entire expression to the right of `be of`/`*=` should be evaluated first, and then the multiplication should happen at the end (just before assignment). I think Rocky is doing `total = total * 3 + 5` (where multiplication has higher precedence than addition) when it should be doing `total = total * (3 + 5)`.

**Comment by gaborsch** [comment]
Nice catch! Actually the spec does not say anything about the RHS, but it clearly says that this construct should represent the `*=` compound statement.

It needs some refactoring, though.

**Comment by gaborsch** [comment]
Fixed!
