### ISSUE TITLE
String escaping broken

### ISSUE THREAD

**Issue by sisyphus-ppcg** [gaborsch/rocky#51]
String escapes are currently broken:

```
say "abc\ndef"
```

Expected:

```
abc
def
```

Actual:

```
abc\ndef
```

I think the problem lies at https://github.com/gaborsch/rocky/blob/2b72816a67a92b23f0664593265b46670d34ba3f/src/rockstar/parser/ExpressionParser.java#L138

`replace` does not take a regex, it should be `replaceAll`

**Comment by gaborsch** [comment]
Good catch, fixed.

**Comment by gaborsch** [comment]
Good catch, fixed.
