### ISSUE TITLE
Negative zero is truthy

### ISSUE THREAD

**Issue by Andriamanitra** [gaborsch/rocky#52]
Code to reproduce:
```rockstar
If 0 * -1
Shout "Negative zero is truthy"
Else
Shout "Negative zero is falsy"

If 0 * 1
Shout "Positive zero is truthy"
Else
Shout "Positive zero is falsy"
```

According to the [language spec](https://github.com/RockstarLang/rockstar/blob/main/spec.md#truthiness) numbers that are equal to zero should be falsy:
> Number - If equal to zero, falsy. Otherwise, truthy.

**Comment by gaborsch** [comment]
Good catch, actually it's a Java quirk. Fixed.
