### ISSUE TITLE
`Join` ignores leading empty strings

### ISSUE THREAD

**Issue by btnlq** [gaborsch/rocky#53]
```c
rock array with "", "", "abc", "def"
join array with "|"
shout array
```
Expected:
```
||abc|def
```
Actual:
```
abc|def
```
I think this is because of
https://github.com/gaborsch/rocky/blob/297309d8fcd3b13e553b3388ace3c694a1636d6c/src/rockstar/statement/JoinStatement.java#L38-L40
`sb` is still empty after the first iteration.

**Comment by gaborsch** [comment]
Good catch, that was the reason. Feel free to submit a PR!
