### ISSUE TITLE
`and`/`or` returns a boolean value instead of the second operand

### ISSUE THREAD

**Issue by btnlq** [gaborsch/rocky#54]
`and`/`or` returns a boolean value if it doesn't short circuit:
```c
shout 0 or 42
shout 0 or 0
shout 16 and 42
shout 16 and 0
```
Expected (Satriani):
```c
42
0
42
0
```
Actual:
```c
true
false
true
false
```
It works as expected if it short circuits:
```c
shout 16 or 42
shout 16 or 0
shout 0 and 42
shout 0 and 0
```
Expected/Actual:
```c
16
16
0
0
```

**Comment by gaborsch** [comment]
Thanks for the detailed bug report, fixed!

I also discovered that with mixed operands (number and boolean, boolean and number, etc.) Satriani behaves differently than Rocky, but it is not covered by the specification, so no one should rely on that.

**Comment by btnlq** [comment]
If I understand correctly, a logical operator on non-boolean operands now always returns the first operand. For example, `0 or 42` results in `0`, but `truthy or falsey` should result in `truthy`.

I meant something like this (not tested): 

```diff
    switch (type) {
        case AND:
            if (v1.asBoolean().equals(Value.BOOLEAN_TRUE)) {
-               return ctx.afterExpression(this, v1.and(expr2.evaluate(ctx)));
+               return ctx.afterExpression(this, expr2.evaluate(ctx));
            }
            return ctx.afterExpression(this, v1);
        case OR:
            if (v1.asBoolean().equals(Value.BOOLEAN_FALSE)) {
-               return ctx.afterExpression(this, v1.and(expr2.evaluate(ctx)));
+               return ctx.afterExpression(this, expr2.evaluate(ctx));
            }
            return ctx.afterExpression(this, v1);
        case NOR:
            if (v1.asBoolean().equals(Value.BOOLEAN_FALSE)) {
                return ctx.afterExpression(this, v1.nor(expr2.evaluate(ctx)));
            }
            return ctx.afterExpression(this, Value.BOOLEAN_FALSE);
    }
```

(

**Comment by gaborsch** [comment]
Actually, you were right. I didn't get the logic for Satriani's behaviour first, but now it's OK.
We check if the first operand is truthy or falsy, and observing that we return either the first or the second operand as a result (the first operand in case of shortcut, the second otherwise)
Now it should work as Satriani.
