### ISSUE TITLE
Parser removes punctuation inside a string

### ISSUE THREAD

**Issue by btnlq** [gaborsch/rocky#55]
```c
shout ";("
```
prints ` (`. I think it's because `readBuffer` doesn't know that `(` is inside a string:
https://github.com/gaborsch/rocky/blob/fecffb95670a73860bfc11f146b50317745b5ce7/src/rockstar/parser/MultilineReader.java#L76

**Comment by gaborsch** [comment]
Tricky bug, had to deal with the terminating commas (also before a left parenthesis), and the single dot wanted to become a decimal number, but all resolved.
