### ISSUE TITLE
Pushing a string with a trailing \ silently does nothing?

### ISSUE THREAD

**Issue by JRaspass** [gaborsch/rocky#57]
```
rock foo
rock "a" into foo
rock "b\\" into foo
rock "\\" into foo
rock "\\c" into foo
rock "d" into foo

while foo alike bar
shout bar
```
```
a
\c
d
```
Where'd `b\` and `\` go?

**Comment by JRaspass** [comment]
Fairly sure this was caused by https://github.com/gaborsch/rocky/commit/66606af791ec5e31a570d7786dc81d14b4db3cac

**Comment by gaborsch** [comment]
That was a tricky one, thanks for the example!

**Comment by JRaspass** [comment]
Thanks for the speedy fix, works my end :+1:
