### ISSUE TITLE
"All values/keys of" is unreachable in parser

### ISSUE THREAD

**Issue by GrayJoKing** [gaborsch/rocky#59]
Specifically starting at [this line](https://github.com/gaborsch/rocky/blob/cc572672c5d2fe8120c28039a044a04cfa82fb3f/src/rockstar/parser/ExpressionParser.java#L525) , the block parsing length 3 statements in the format "all x of" is unreachable due to the check in the previous branch of the if-else statement. This can probably be easily fixed by moving the third block above the second.

**Comment by gaborsch** [comment]
The `all keys of` and `all values of` intenal functions were also obsolete, but since there is a need for that, I fixed it (and raised to a feature). 
The code you pointed at was actually buggy, it checked `all of keys` and `all of values`, wrongly (and as you  pointed out, was als unreachable).
