### ISSUE TITLE
`break` doesnt exit loop

### ISSUE THREAD

**Issue by MeWhenI** [gaborsch/rocky#61]
```
x = 1
while x - 10
 break it down
 say x
 x = x + 1
```
This code should exit without outputting anything, but instead carries out the full loop, outputting numbers 1-9.

**Comment by gaborsch** [comment]
Thanks for the bug report and the example! For some reason we had removed the test for the `break` statement, and eventually this feature was turned off for Rocky extension mode. 

Now I restored it for all modes, and also added the old test to the current test set.
