### ISSUE TITLE
"'s" with poetic number literals containing "is"

### ISSUE THREAD

**Issue by hapaxlego** [gaborsch/rocky#9]
`my word is misspelled`
`say my word`
outputs 6.
It seems to occur only with "'s" and literals containing "is", returning the number of characters following the first/only "is" -1.
is misspelled, was misspelled, 's mespelled and 's washed work just fine.

**Comment by gaborsch** [comment]
Cannot reproduce it, it works fine for me:

```
$ cat a.rock
my word is misspelled
say my word
my word's misspelled
say my word
```
Result:
```
$ ./rockstar a.rock
0
0
```

Even the listing says it's 0, not 6:
```
$ ./rockstar list -x a.rock

PROGRAM a.rock
  my word is misspelled
  my word := 0
  say my word
  print my word
  my word's misspelled
  my word := 0
  say my word
  print my word
```

Could you give me an example, and the version of code you use? (Perhaps the jar file date and file size will help)

**Comment by hapaxlego** [comment]
It says 0.99 on the readme and on console, size 277 KB. Java 8 is installed. I seem to get the same error on a different mahine/OS.

**Comment by gaborsch** [comment]
Managed to reproduce, will fix soon.

**Comment by gaborsch** [comment]
Fixed.
